[tools]
"github:yt-dlp/yt-dlp" = "latest"
"go:github.com/asimihsan/mcp-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@kimuson/claude-code-viewer" = "latest"
"npm:@marp-team/marp-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:linearis" = "latest"
"npm:vibe-kanban" = "latest"
"pipx:aider-chat" = "latest"
"pipx:copier" = "latest"
"pipx:ipython" = "latest"
"pipx:llm" = "latest"
"pipx:marker-pdf[full]" = "latest"
"pipx:mcp-proxy" = "latest"
"pipx:parquet-tools" = "latest"
"pipx:playwright" = "latest"
"ubi:idursun/jjui" = "latest"
"ubi:jandedobbeleer/aliae" = "latest"
"ubi:mufeedvh/code2prompt" = "latest"

"cargo:asciinema" = "latest"
"cargo:atuin" = "latest"
"cargo:ck-search" = "latest"
"cargo:eza" = "latest"
"cargo:git-delta" = "latest"
"cargo:https://github.com/terhechte/cursor-rust-tools" = "latest"
"cargo:lazyjj" = "latest"
"cargo:lstr" = "latest"
"cargo:mergiraf" = "latest"
"cargo:monolith" = "latest"
"cargo:sccache" = "latest"
"cargo:taplo-cli" = "latest"

1password = "latest"
age = "latest"
aws-vault = "latest"
awscli = { version = "2.32.21", symlink_bins = "true" }
bun = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
difftastic = "latest"
direnv = "latest"
dotnet = "latest"
duckdb = "latest"
dust = "latest"
fd = "latest"
ffmpeg = "latest"
flutter = "latest"
fzf = "latest"
gh = "latest"
go = "prefix:1.25"
golangci-lint = "latest"
gradle = "latest"
helm = "latest"
java = "prefix:corretto-21"
jq = "latest"
jujutsu = "latest"
just = "latest"
k9s = "latest"
ktlint = "latest"
neovim = "latest"
node = "25"
oapi-codegen = "latest"
opentofu = "latest"
pandoc = "latest"
pnpm = "latest"
python = "prefix:3.12"
rclone = "latest"
restic = "latest"
ripgrep = "latest"
ruby = "prefix:3.4"
"rust" = { version = "prefix:1.91", components = "rust-docs,rustfmt,clippy,rust-analyzer" }
shellcheck = "latest"
starship = "latest"
terraform = "latest"
uv = "latest"
yq = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
"gem:fpm" = "latest"

[env]
AWS_ASSUME_ROLE_TTL = "4h"
AWS_CHAINED_SESSION_TOKEN_TTL = "4h"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "rust"]
npm.bun = true
auto_install = false

[hooks]
postinstall = [
    "~/bin/fix-mise-awscli.sh"
]
