# Disable the blank line at the start of the prompt
add_newline = false

# Set a reasonable timeout for directory scans
scan_timeout = 30

# Customize the prompt format
format = """
[î‚¶](#BA1861)\
$username\
[î‚°](bg:#DB4678 fg:#BA1861)\
$directory\
[î‚°](fg:#DB4678 bg:#E87D8C)\
$git_branch\
$git_status\
[î‚°](fg:#E87D8C bg:#89ABCE)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$nix_shell\
$rust\
[î‚°](fg:#89ABCE bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚° ](fg:#33658A)\
"""

right_format = """${cmd_duration}
$memory_usage$battery"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#BA1861"
style_root = "bg:#BA1861"
format = '[$user ]($style)'

[directory]
style = "bg:#DB4678"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ğŸ“„ "
"Downloads" = "â¬‡ï¸ "
"Music" = "ğŸµ "
"Pictures" = "ğŸ–¼ï¸ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ï„• ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ï„•  " = " ï„• ï„ª "

[c]
symbol = "ğŸ…’ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[docker_context]
symbol = "ğŸ³ "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = "ğŸ’§ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[elm]
symbol = "ğŸŒ³ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[git_branch]
symbol = "ğŸŒ¿ "
style = "bg:#E87D8C"
format = '[[ $symbol $branch ](bg:#E87D8C)]($style)'

[git_status]
style = "bg:#E87D8C"
format = '[[($all_status$ahead_behind )](bg:#E87D8C)]($style)'

[golang]
symbol = "ğŸ¹ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[haskell]
symbol = "Î» "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[java]
symbol = "â˜• "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[julia]
symbol = "à®ƒ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[nodejs]
symbol = "ğŸŸ¢ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[nim]
symbol = "ğŸ‘‘ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[nix_shell]
symbol = "â„ï¸ "
style = "bg:#89ABCE"
format = '[[ $symbol $state ](bg:#89ABCE)]($style)'

[rust]
symbol = "ğŸ¦€ "
style = "bg:#89ABCE"
format = '[[ $symbol ($version) ](bg:#89ABCE)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ î™ $time ](bg:#33658A)]($style)'

[cmd_duration]
min_time = 100  # Show duration for commands that take 100ms or longer
format = "took [$duration](bold yellow)"

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

# [git_status]
# conflicted = "âš”ï¸"
# ahead = "ğŸğŸ’¨Ã—${count}"
# behind = "ğŸ¢Ã—${count}"
# diverged = "ğŸ”± ğŸğŸ’¨Ã—${ahead_count} ğŸ¢Ã—${behind_count}"
# untracked = "ğŸ›¤ï¸Ã—${count}"
# modified = "ğŸ“Ã—${count}"
# staged = "ğŸ—ƒï¸Ã—${count}"
# renamed = "ğŸ“›Ã—${count}"
# deleted = "ğŸ—‘ï¸Ã—${count}"

[python]
symbol = "ğŸ "
pyenv_version_name = true
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[memory_usage]
disabled = false
threshold = 75
symbol = "ğŸ§  "
style = "bold dimmed white"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 10
style = "bold red"
