file_opener = "cursor"
approval_policy = "on-failure"
sandbox_mode = "workspace-write"
tool_timeout_sec = 600

model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed" # auto, concise, detailed
model_verbosity = "high" # low, medium, high
web_search = "live"

# [mcp_servers.context7]
# command = "npx"
# args = ["-y", "@upstash/context7-mcp"]

# [mcp_servers.fetch]
# command = "uvx"
# args = ["mcp-server-fetch"]

# [mcp_servers.aws-api]
# command = "uvx"
# args = ["awslabs.aws-api-mcp-server@latest"]
# env = { "AWS_REGION"="us-west-2" }

# [mcp_servers.aws_docs]
# command = "uvx"
# args = ["fastmcp", "run", "https://knowledge-mcp.global.api.aws"]

# [mcp_servers.go-language-server]
# command = "mcp-language-server"
# args = ["--workspace", ".", "--lsp", "gopls"]

# [mcp_servers.rust-language-server]
# command = "mcp-language-server"
# args = ["--workspace", ".", "--lsp", "rust-analyzer"]

# [mcp_servers.python-language-server]
# command = "mcp-language-server"
# args = ["--workspace", ".", "--lsp", "uv", "--", "run", "basedpyright-langserver", "--stdio"]

# [mcp_servers.linear]
# url = "https://mcp.linear.app/mcp"

# [mcp_servers.github]
# url = "https://api.githubcopilot.com/mcp/"
# bearer_token_env_var = "GITHUB_LEVELSERVER_PAT"

[features]
multi_agent = true
rmcp_client = true
shell_snapshot = true
skills = true
steer = true
unified_exec = true
prevent_idle_sleep = true

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
